owner: jeremibiz
repo: upptime

sites:
  - name: Main - jeremi.fr.to
    url: https://jeremi.fr.to
  - name: Index - morphy.fr.to
    url: https://morphy.fr.to
  - name: Project - project-morphy.fr.to
    url: https://project-morphy.fr.to

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "jeremi.fr.to"
  introMessage: upptime pages 
  navbar:
    - title: Index
      href: https://morphy.fr.to
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
